import { Badge } from "react-bootstrap";

const ReportContent = ({ report }) => {
  if (!report) return null;

  return (
    <div className="report-content">
      {report.title && <h5 className="mb-3">{report.title}</h5>}

      {report.summary && (
        <div className="mb-4">
          <h4 className="text-muted mb-2">Summary</h4>
          <p>{report.summary}</p>
        </div>
      )}

      {report.changes && report.changes.length > 0 && (
        <div className="mb-4">
          <h4 className="text-muted mb-2">Changes</h4>
          <ul className="mb-0">
            {report.changes.map((change, idx) => (
              <li key={idx}>{change}</li>
            ))}
          </ul>
        </div>
      )}

      {report.rationale && (
        <div className="mb-4">
          <h4 className="text-muted mb-2">Rationale</h4>
          <p>{report.rationale}</p>
        </div>
      )}

      {report.impact_and_tests && (
        <div className="mb-4">
          <h4 className="text-muted mb-2">Impact & Tests</h4>
          <p>{report.impact_and_tests}</p>
        </div>
      )}

      {report.next_steps && report.next_steps.length > 0 && (
        <div className="mb-4">
          <h4 className="text-muted mb-2">Next Steps</h4>
          <ul className="mb-0">
            {report.next_steps.map((step, idx) => (
              <li key={idx}>{step}</li>
            ))}
          </ul>
        </div>
      )}

      {report.tags && (
        <div className="mb-3">
          <h4 className="text-muted mb-2">Tags</h4>
          <div className="d-flex flex-wrap gap-1">
            {report.tags.split(",").map((tag, idx) => (
              <Badge key={idx} bg="light" text="dark" className="fw-normal">
                {tag.trim()}
              </Badge>
            ))}
          </div>
        </div>
      )}

      <div className="border-top pt-3 mt-3">
        <small className="text-muted">
          Generated by <strong>{report.provider_used || "AI"}</strong>
          {report.generation_time_ms && (
            <> in {(report.generation_time_ms / 1000).toFixed(2)}s</>
          )}
        </small>
      </div>
    </div>
  );
};

export default ReportContent;

